#!/bin/bash
#
# Copyright (C) 2020 azrim.
# All rights reserved.

# VAR
DIR=$PWD
TAG=$1

qcacld="https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/qcacld-3.0"
fw_api="https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/fw-api"
qca_wifi_host_cmn="https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/wlan/qca-wifi-host-cmn"
audio="https://git.codelinaro.org/clo/la/platform/vendor/opensource/audio-kernel"
data="https://git.codelinaro.org/clo/la/platform/vendor/qcom-opensource/data-kernel"
wg="https://github.com/WireGuard/wireguard-linux-compat.git"
exfat="https://github.com/arter97/exfat-linux"

merge() {
    [[ ! -d "$DIR/drivers/staging/qcacld-3.0" ]] && git subtree add --prefix drivers/staging/qcacld-3.0 $qcacld $TAG || git subtree pull --prefix drivers/staging/qcacld-3.0 $qcacld $TAG
    [[ ! -d "$DIR/drivers/staging/fw-api" ]] && git subtree add --prefix drivers/staging/fw-api $fw_api $TAG || git subtree pull --prefix drivers/staging/fw-api $fw_api $TAG
    [[ ! -d "$DIR/drivers/staging/qca-wifi-host-cmn" ]] && git subtree add --prefix drivers/staging/qca-wifi-host-cmn $qca_wifi_host_cmn $TAG || git subtree pull --prefix drivers/staging/qca-wifi-host-cmn $qca_wifi_host_cmn $TAG
    [[ ! -d "$DIR/techpack/audio" ]] && git subtree add --prefix techpack/audio $audio $TAG || git subtree pull --prefix techpack/audio $audio $TAG
    [[ ! -d "$DIR/techpack/data" ]] && git subtree add --prefix techpack/data $data $TAG || git subtree pull --prefix techpack/data $data $TAG
    [[ ! -d "$DIR/fs/exfat" ]] && git subtree add --prefix fs/exfat $exfat master || git subtree pull --prefix fs/exfat $exfat master
    [[ ! -d "$DIR/net/wireguard" ]] && git subtree add --prefix net/wireguard $wg master || git subtree pull --prefix net/wireguard $wg master
}

merge
